apiVersion: v1
kind: Pod
metadata:
  name: store-engine-eshop-product-loader-ms-pod
  labels:
    app: store-engine-eshop-product-loader-ms
spec:
  containers:
  - name: store-engine-eshop-product-loader-ms-container
    image: store-engine-eshop-product-loader-ms:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3006
    env:
    - name: NODE_ENV
      value: "production"
    - name: MONGODB_CONNECTION_STRING
      value: "mongodb://host.docker.internal:27017/mydb"
    
